In [1]:
import pandas as pd

Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [2]:
Hut_Paradise_values = Hut_Paradise_DF.values

In [3]:
Hut_Paradise_values[4]

array([40, 33,  1,  6, 20, 16], dtype=int64)

In [4]:
Hut_Paradise_values[:, 3]

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5], dtype=int64)

In [8]:
Hut_Paradise_values[:, 1] - Hut_Paradise_values[:, 5]

array([13, 12, 15, 13, 17,  9, 20, 15, 25], dtype=int64)

In [9]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])